import type { Metadata } from "next";

import fonts from "@/config/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          as="video"
          href="/videos/intro.mp4"
          type="video/mp4"
        />
      </head>
      <body
        className={`${fonts.title.variable} ${fonts.default.variable}  ${fonts.default.className} ${fonts.skills.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
